apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: projet-eni
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 1tanguy/projet-devops:backend-2d50d4c
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: todolist-config
            - secretRef:
                name: todolist-secrets
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: todolist-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: todolist-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todolist-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todolist-secrets
                  key: MYSQL_ROOT_PASSWORD
      tolerations:           
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"