apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: projet-eni
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:                
    metadata:
      labels:
        app: mysql
    spec:                  
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: todolist-secrets
            - configMapRef:
                name: todolist-config
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: todolist-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: todolist-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todolist-secrets
                  key: DB_PASSWORD
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todolist-secrets
                  key: DB_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
      tolerations:           
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"
