apiVersion: v1
kind: Secret
metadata:
  namespace: projet-eni
  name: todolist-secrets
type: Opaque
data:
  MYSQL_USER: dXNlcg==        
  MYSQL_PASSWORD: cGFzc3dvcmQ=  
  MYSQL_ROOT_PASSWORD: cm9vdA==  
